# Generated by Django 2.2.6 on 2019-11-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='insitute',
            new_name='institute',
        ),
    ]
