# Generated by Django 2.2.6 on 2019-10-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='logos'),
        ),
    ]
