# Generated by Django 3.0.5 on 2020-06-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_auto_20200614_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logoFile',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
