# Generated by Django 2.2.6 on 2019-10-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_auto_20191021_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='research',
            name='year',
        ),
        migrations.AddField(
            model_name='article',
            name='resume',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AddField(
            model_name='presentation',
            name='resume',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presentation',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AddField(
            model_name='research',
            name='projects',
            field=models.ManyToManyField(to='productivity.Project', verbose_name='related projects'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='resume',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='thesis',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
