# Generated by Django 2.2.6 on 2019-11-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_auto_20191116_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lines',
            field=models.ManyToManyField(blank=True, to='productivity.Line', verbose_name='interest areas'),
        ),
    ]
