# Generated by Django 2.2.6 on 2019-11-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_auto_20191116_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='productivity.Member', verbose_name='collaborators'),
        ),
    ]
