# Generated by Django 2.2.6 on 2019-10-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_auto_20191023_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='event',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
