# Generated by Django 3.0.5 on 2020-06-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_auto_20200614_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
