# Generated by Django 2.2.6 on 2019-11-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0004_auto_20191124_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
