# Generated by Django 3.0.5 on 2020-07-17 05:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0004_auto_20200614_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='roles',
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, size=20),
        ),
    ]
