# Generated by Django 2.2.6 on 2019-11-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_auto_20191125_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='charge',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
