# Generated by Django 3.0.5 on 2020-07-17 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0006_auto_20200717_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lines',
        ),
        migrations.AddField(
            model_name='project',
            name='lines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, null=True, size=20),
        ),
    ]
