# Generated by Django 2.2.6 on 2019-12-01 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0006_auto_20191130_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('QR', models.URLField(blank=True, default='', max_length=100)),
                ('photo', models.URLField(blank=True, default='', max_length=100)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('exp', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 2, 22, 13, 20, 558246))),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productivity.Membership'),
        ),
    ]
