# Generated by Django 2.2.6 on 2019-12-01 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0007_auto_20191201_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 2, 22, 44, 28, 763772)),
        ),
    ]
