# Generated by Django 2.2.6 on 2019-12-01 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0008_auto_20191201_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 2, 23, 7, 51, 497443)),
        ),
    ]
