# Generated by Django 3.0.5 on 2021-01-04 01:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0008_auto_20200717_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='adscription',
        ),
        migrations.RemoveField(
            model_name='member',
            name='board',
        ),
        migrations.RemoveField(
            model_name='member',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='member',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='member',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='thumbnailFile',
        ),
        migrations.AddField(
            model_name='member',
            name='dateJoined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, null=True, size=20),
        ),
    ]
