# Generated by Django 2.2.6 on 2019-12-07 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0010_auto_20191201_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='logo',
            new_name='logoFile',
        ),
        migrations.AddField(
            model_name='partner',
            name='logoName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 8, 5, 26, 23, 359102)),
        ),
    ]
