# Generated by Django 2.2.6 on 2019-12-07 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0011_auto_20191207_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='site',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 8, 5, 40, 47, 911847)),
        ),
    ]
