# Generated by Django 2.2.6 on 2019-12-07 06:50

import datetime
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0012_auto_20191207_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='thumbnailFile',
            field=models.ImageField(blank=True, default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='thumbnail'),
        ),
        migrations.AddField(
            model_name='member',
            name='thumbnailUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 8, 6, 50, 38, 948578)),
        ),
    ]
