# Generated by Django 2.2.6 on 2019-12-08 02:26

import datetime
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0015_auto_20191208_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='thumbnailFile',
            field=models.ImageField(default=None, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='thumbnail'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 9, 2, 25, 59, 868976)),
        ),
    ]
