# Generated by Django 2.2.6 on 2019-12-08 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0029_auto_20191208_0808'),
        ('productivity', '0017_auto_20191208_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.Income'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 9, 8, 8, 13, 481413)),
        ),
    ]
