# Generated by Django 2.2.6 on 2019-12-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0018_auto_20191208_0808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
