# Generated by Django 2.2.6 on 2019-12-08 19:56

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0019_delete_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='logo',
            field=models.ImageField(blank=True, default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='logos'),
        ),
    ]
