# Generated by Django 2.2.6 on 2019-12-08 21:54

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0020_auto_20191208_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='thumbnailFile',
            field=models.ImageField(default='https://drive.google.com/uc?id=', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='thumbnail'),
        ),
    ]
