# Generated by Django 2.2.6 on 2019-12-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0022_auto_20191208_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fullname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
