# Generated by Django 2.2.6 on 2019-12-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0024_auto_20191209_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='adscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adscription_institute', to='productivity.Partner'),
        ),
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(blank=True, to='productivity.Role', verbose_name='list of roles'),
        ),
    ]
