# Generated by Django 2.2.6 on 2019-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0025_auto_20191209_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='thumbnailUrl',
        ),
        migrations.AddField(
            model_name='member',
            name='committee',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
