# Generated by Django 2.2.6 on 2019-12-13 17:55

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0026_auto_20191213_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='thumbnailFile',
            field=models.ImageField(blank=True, default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='thumbnail'),
        ),
    ]
