# Generated by Django 2.2.6 on 2020-01-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0027_auto_20191213_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='productivity.Division', verbose_name='members'),
        ),
    ]
