# Generated by Django 2.2.6 on 2019-12-08 19:56

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('DIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='DIS'),
        ),
    ]
