# Generated by Django 2.2.6 on 2019-10-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIS', '0002_auto_20191006_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
        migrations.AlterField(
            model_name='pet',
            name='peso',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
