# Generated by Django 2.2.6 on 2019-10-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIS', '0003_auto_20191006_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='peso',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
