# Generated by Django 2.2.6 on 2019-10-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIS', '0005_auto_20191006_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
