# Generated by Django 2.2.6 on 2019-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIS', '0006_auto_20191006_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vacunas',
            field=models.ImageField(blank=True, default=None, upload_to='pets'),
        ),
    ]
