# Generated by Django 2.2.6 on 2019-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIS', '0007_auto_20191006_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, default=None, upload_to='pets'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vacunas',
            field=models.TextField(blank=True),
        ),
    ]
