# Generated by Django 2.2.6 on 2019-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIS', '0008_auto_20191006_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.URLField(blank=True, default=''),
        ),
    ]
