# Generated by Django 2.2.6 on 2019-10-05 21:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, default='')),
                ('to', models.CharField(max_length=100)),
                ('qr_url', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, default='', upload_to='certs')),
            ],
        ),
    ]
