# Generated by Django 2.2.6 on 2019-10-05 22:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, default='')),
                ('to', models.CharField(max_length=100)),
                ('qr_url', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, default='', upload_to='certs')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(blank=True)),
                ('date_end', models.DateTimeField(blank=True)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('flyer', models.ImageField(default=None, null=True, upload_to='flyers')),
            ],
        ),
    ]
