# Generated by Django 3.0.5 on 2020-06-13 20:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='RECOGNITION', max_length=100)),
                ('event', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('published', models.BooleanField(default=False)),
                ('to', models.CharField(blank=True, default='', max_length=100)),
                ('QR', models.CharField(blank=True, default='www.aaaimx.org/certificates/?id=', max_length=100)),
                ('file', models.ImageField(blank=True, upload_to='certs')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('stock', models.IntegerField(blank=True, default=0)),
                ('available', models.IntegerField(blank=True, default=0)),
                ('observations', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('date_start', models.DateTimeField(blank=True)),
                ('date_end', models.DateTimeField(blank=True)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('flyer', models.ImageField(blank=True, default=None, null=True, upload_to='flyers')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productivity.Division')),
            ],
        ),
    ]
