# Generated by Django 3.0.5 on 2020-07-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20200719_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
