# Generated by Django 2.2.6 on 2019-11-22 06:26

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20191122_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='QR',
            field=models.CharField(blank=True, default='www.aaaimx.org/certificates/', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='certs'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='to',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
