# Generated by Django 2.2.6 on 2019-11-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_auto_20191122_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.CharField(blank=True, default='Recognition', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
