# Generated by Django 3.0.5 on 2020-12-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_auto_20200719_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('enrollment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('career', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('adscription', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.Event'),
        ),
    ]
