# Generated by Django 2.2.6 on 2019-12-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_auto_20191122_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='QR',
            field=models.CharField(blank=True, default='www.aaaimx.org/certificates/?id=', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(blank=True, default='RECOGNITION', max_length=100),
        ),
    ]
