# Generated by Django 3.0.5 on 2021-01-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_auto_20210101_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cc_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
