# Generated by Django 2.2.6 on 2020-01-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
