# Generated by Django 3.0.5 on 2021-01-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_participant_cc_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open_to_public',
            field=models.BooleanField(default=False),
        ),
    ]
