# Generated by Django 3.0.5 on 2021-01-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0008_event_open_to_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='surname',
        ),
        migrations.AddField(
            model_name='participant',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
    ]
