# Generated by Django 2.2.6 on 2020-03-16 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_auto_20200122_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
