# Generated by Django 3.0.5 on 2021-01-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_auto_20210102_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cc_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
