# Generated by Django 3.0.5 on 2021-01-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_certificate_has_custom_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ftp_folder',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
