# Generated by Django 3.0.5 on 2021-01-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_certificate_ftp_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='has_custom_file',
        ),
    ]
