# Generated by Django 3.0.5 on 2020-06-09 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0028_auto_20200124_0725'),
        ('logistic', '0012_auto_20200609_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productivity.Division'),
        ),
    ]
