# Generated by Django 3.0.5 on 2021-01-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0015_certificate_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='event_title',
        ),
    ]
