# Generated by Django 3.0.5 on 2021-01-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0016_remove_certificate_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='responsible',
            field=models.BooleanField(default=False),
        ),
    ]
