# Generated by Django 3.0.5 on 2021-01-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0018_auto_20210113_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='published',
        ),
        migrations.AddField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
