# Generated by Django 3.0.5 on 2021-02-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0020_auto_20210208_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
