# Generated by Django 2.2.6 on 2019-10-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, default='', max_length=100)),
                ('concept', models.TextField(blank=True, default='')),
                ('division', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, default='', max_length=100)),
                ('concept', models.TextField(blank=True, default='')),
                ('division', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('type', models.TextField(blank=True, default='')),
            ],
        ),
    ]
