# Generated by Django 3.0.5 on 2020-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='concept',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='to',
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='voucher',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
