# Generated by Django 2.2.6 on 2019-11-14 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_auto_20191023_0438'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('QR', models.URLField(blank=True, default='', max_length=100)),
                ('photo', models.URLField(blank=True, default='', max_length=100)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('exp', models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 21, 7, 31, 130434))),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.Income')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.Member')),
            ],
        ),
    ]
