# Generated by Django 3.0.5 on 2020-07-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20200720_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='issued_at',
            new_name='created_at',
        ),
    ]
