# Generated by Django 2.2.6 on 2019-11-14 21:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 21, 11, 2, 869184)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
