# Generated by Django 2.2.6 on 2019-10-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_adminexpense_adminincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindonation',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='admindonation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admindonation',
            name='division',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admindonation',
            name='donor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adminexpense',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='adminexpense',
            name='concept',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adminincome',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='adminincome',
            name='concept',
            field=models.TextField(blank=True, default=''),
        ),
    ]
