# Generated by Django 3.0.5 on 2021-01-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20200720_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='file',
            field=models.ImageField(blank=True, upload_to='memberships'),
        ),
    ]
