# Generated by Django 2.2.6 on 2019-10-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20191006_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(blank=True, default='')),
                ('concept', models.TextField(blank=True, default='')),
                ('division', models.TextField(blank=True, default='')),
                ('amount', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_what', models.TextField(blank=True, default='')),
                ('concept', models.TextField(blank=True, default='')),
                ('division', models.TextField(blank=True, default='')),
                ('amount', models.FloatField(blank=True, default=0)),
                ('type', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminDonation',
        ),
        migrations.DeleteModel(
            name='AdminExpense',
        ),
        migrations.DeleteModel(
            name='AdminIncome',
        ),
    ]
