# Generated by Django 2.2.6 on 2019-10-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20191006_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='from_what',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
