# Generated by Django 2.2.6 on 2019-10-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20191006_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='division',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='division',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
