# Generated by Django 2.2.6 on 2019-11-22 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_auto_20191122_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 23, 19, 16, 40, 731067)),
        ),
    ]
