# Generated by Django 2.2.6 on 2019-11-23 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_auto_20191122_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 24, 1, 0, 26, 777157)),
        ),
    ]
