# Generated by Django 2.2.6 on 2019-11-24 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_auto_20191123_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 25, 19, 41, 5, 170091)),
        ),
    ]
