# Generated by Django 2.2.6 on 2019-11-24 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_auto_20191124_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 25, 20, 39, 21, 256646)),
        ),
    ]
