# Generated by Django 2.2.6 on 2019-11-25 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_auto_20191125_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 26, 2, 2, 55, 354832)),
        ),
    ]
