# Generated by Django 2.2.6 on 2019-11-25 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_auto_20191125_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 26, 4, 12, 11, 913218)),
        ),
    ]
