# Generated by Django 2.2.6 on 2019-11-25 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_auto_20191125_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 26, 4, 13, 55, 242899)),
        ),
    ]
