# Generated by Django 2.2.6 on 2019-11-27 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_auto_20191127_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 28, 5, 35, 51, 241173)),
        ),
    ]
