# Generated by Django 2.2.6 on 2019-11-27 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0024_auto_20191127_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 28, 6, 43, 8, 475161)),
        ),
    ]
