# Generated by Django 2.2.6 on 2019-11-30 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0025_auto_20191127_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 1, 4, 29, 3, 620194)),
        ),
    ]
