# Generated by Django 2.2.6 on 2019-11-30 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0026_auto_20191130_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 1, 21, 35, 27, 817949)),
        ),
    ]
