# Generated by Django 2.2.6 on 2019-12-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0027_auto_20191130_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
