# Generated by Django 2.2.6 on 2019-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0028_delete_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='division',
        ),
        migrations.RemoveField(
            model_name='income',
            name='division',
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
