# Generated by Django 2.2.6 on 2019-12-08 08:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0019_delete_membership'),
        ('finances', '0029_auto_20191208_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, default='', max_length=100)),
                ('origin', models.CharField(blank=True, default='', max_length=100)),
                ('concept', models.TextField(blank=True, default='')),
                ('amount', models.FloatField(blank=True, default=0)),
                ('type', models.TextField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('QR', models.URLField(blank=True, default='', max_length=100)),
                ('exp', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 9, 8, 18, 41, 74211))),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.BankMovement')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productivity.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
