# Generated by Django 2.2.6 on 2019-12-08 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0030_auto_20191208_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovement',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 9, 8, 21, 41, 739853)),
        ),
    ]
