# Generated by Django 2.2.6 on 2019-12-08 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0032_auto_20191208_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 9, 21, 54, 17, 903700)),
        ),
    ]
