# Generated by Django 2.2.6 on 2019-12-08 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0033_auto_20191208_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 9, 21, 58, 25, 913545)),
        ),
    ]
