# Generated by Django 2.2.6 on 2019-12-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0034_auto_20191208_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
