# Generated by Django 2.2.6 on 2019-12-13 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0040_auto_20191213_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 14, 17, 55, 31, 893292)),
        ),
    ]
