# Generated by Django 2.2.6 on 2020-01-09 07:29

import datetime
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0041_auto_20191213_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='income',
        ),
        migrations.AddField(
            model_name='membership',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='membership',
            name='file',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='memberships'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 10, 7, 29, 5, 378746)),
        ),
    ]
