# Generated by Django 2.2.6 on 2020-01-10 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0042_auto_20200109_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 11, 5, 12, 48, 690594)),
        ),
    ]
