# Generated by Django 2.2.6 on 2020-01-22 08:13

import datetime
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0044_auto_20200122_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovement',
            name='file',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='vouchers/%Y-%m-%D/'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 8, 13, 38, 307585)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='file',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='memberships'),
        ),
    ]
