# Generated by Django 2.2.6 on 2020-01-22 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0045_auto_20200122_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankmovement',
            old_name='file',
            new_name='voucher',
        ),
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 8, 18, 34, 190282)),
        ),
    ]
