# Generated by Django 2.2.6 on 2020-01-24 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0046_auto_20200122_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 25, 7, 25, 37, 923922)),
        ),
    ]
