# Generated by Django 2.2.6 on 2020-02-04 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0048_auto_20200127_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 5, 1, 6, 33, 629278)),
        ),
    ]
