# Generated by Django 3.0.5 on 2020-04-26 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0051_auto_20200316_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 27, 8, 28, 33, 143752)),
        ),
    ]
