# Generated by Django 3.0.5 on 2020-04-30 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0053_auto_20200426_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 19, 49, 24, 895809)),
        ),
    ]
