# Generated by Django 3.0.5 on 2020-05-01 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0054_auto_20200430_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 2, 4, 11, 24, 256304)),
        ),
    ]
