# Generated by Django 3.0.5 on 2020-05-04 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0055_auto_20200501_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 5, 6, 5, 0, 814901)),
        ),
    ]
