# Generated by Django 3.0.5 on 2020-05-04 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0056_auto_20200504_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 5, 6, 12, 30, 977951)),
        ),
    ]
