# Generated by Django 3.0.5 on 2020-05-09 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0057_auto_20200504_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 10, 8, 13, 9, 706948)),
        ),
    ]
