# Generated by Django 3.0.5 on 2020-05-09 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0060_auto_20200509_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 10, 18, 55, 28, 631075)),
        ),
    ]
