# Generated by Django 3.0.5 on 2020-06-09 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0062_auto_20200609_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 3, 31, 20, 321886)),
        ),
    ]
